# generated by cabal-rpm-0.11.2
# https://fedoraproject.org/wiki/Packaging:Haskell

%global pkg_name notmuch
%global pkgver %{pkg_name}-%{version}

Name:           ghc-%{pkg_name}
Version:        0.1.0.0
Release:        0.20180113%{?dist}
Summary:        Haskell binding to Notmuch, the mail indexer

License:        GPLv3+
Url:            https://hackage.haskell.org/package/%{pkg_name}
Source0:        https://hackage.haskell.org/package/%{pkgver}/%{pkgver}.tar.gz

BuildRequires:  ghc-Cabal-devel
BuildRequires:  ghc-rpm-macros
# Begin cabal-rpm deps:
BuildRequires:  c2hs
BuildRequires:  chrpath
BuildRequires:  ghc-bytestring-devel
BuildRequires:  ghc-containers-devel
BuildRequires:  ghc-mtl-devel
BuildRequires:  ghc-profunctors-devel
BuildRequires:  ghc-tagged-devel
BuildRequires:  ghc-text-devel
BuildRequires:  ghc-time-devel
BuildRequires:  libtalloc-devel%{?_isa}
BuildRequires:  notmuch-devel%{?_isa}
# End cabal-rpm deps

%description
Binding to the notmuch mail indexer, providing a hopefully somewhat typesafe
way to search your email.


%package devel
Summary:        Haskell %{pkg_name} library development files
Provides:       %{name}-static = %{version}-%{release}
Requires:       ghc-compiler = %{ghc_version}
Requires(post): ghc-compiler = %{ghc_version}
Requires(postun): ghc-compiler = %{ghc_version}
Requires:       %{name}%{?_isa} = %{version}-%{release}
# Begin cabal-rpm deps:
Requires:       libtalloc-devel%{?_isa}
Requires:       notmuch-devel%{?_isa}
# End cabal-rpm deps

%description devel
This package provides the Haskell %{pkg_name} library development files.


%prep
%setup -q -n %{pkgver}


%build
%ghc_lib_build


%install
%ghc_lib_install
%ghc_fix_rpath %{pkgver}


%post devel
%ghc_pkg_recache


%postun devel
%ghc_pkg_recache


%files -f %{name}.files
%license gpl-3.0.txt


%files devel -f %{name}-devel.files
%doc README.rst
%{_bindir}/hs-notmuch-files
%{_bindir}/hs-notmuch-tag-count
%{_bindir}/hs-notmuch-tag-message
%{_bindir}/hs-notmuch-tag-set


%changelog
* Sat Jan 13 2018 Fedora Haskell SIG <haskell@lists.fedoraproject.org> - 0.1.0.0-0.20180113
- spec file generated by cabal-rpm-0.11.2
